import {$,$$,initCommon,selectBooking} from './shared.mjs';
import {careQuote,money} from './model.mjs';
import './detailing.css';
let state={size:'M',selected:['polish','ceramic'],zone:'front'};
function summary(){const q=careQuote(state);return `ТАКТ\nРазмер: ${state.size}\n${q.rows.map(r=>`${r.name}: ${money(r.price)}`).join('\n')}\nПлёнка: ${state.selected.includes('film')?(state.zone==='front'?'передняя часть':'весь кузов'):'не выбрана'}\nОриентир: ${money(q.total)}\nСрок: ${q.days} дн.\nДемонстрационный расчёт, не оферта.`;}
function update(){const q=careQuote(state);$$('[data-size]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.size===state.size)));const film=state.selected.includes('film');$$('[data-zone]').forEach(b=>b.setAttribute('aria-pressed',String(film&&b.dataset.zone===state.zone)));$('.care-car').dataset.zone=film?state.zone:'none';$('.car-zone-hint').textContent=film?(state.zone==='front'?'Плёнка: бампер, капот, передние крылья и зеркала.':'Плёнка: все внешние окрашенные элементы кузова.'):'Выберите зону на схеме, чтобы добавить защитную плёнку.';$('[data-care-price]').textContent=q.total?money(q.total):'Не выбраны работы';$('[data-care-days]').textContent=q.days?`${q.days} ${q.days===1?'день':q.days<5?'дня':'дней'}`:'Осмотр';$('[data-care-items]').innerHTML=q.rows.length?q.rows.map(r=>`<div><span>${r.name}${r.key==='film'?` · ${state.zone==='front'?'передняя часть':'весь кузов'}`:''}</span><span>${money(r.price)}</span></div>`).join(''):'<p>Можно начать с осмотра. Подберём работы по состоянию автомобиля.</p>';$('[data-care-book]').innerHTML=q.rows.length?'Выбрать этот уход <span aria-hidden="true">↗</span>':'Запланировать осмотр <span aria-hidden="true">↗</span>';}
$$('[data-size]').forEach(b=>b.addEventListener('click',()=>{state.size=b.dataset.size;update();}));
$$('[name=service]').forEach(input=>input.addEventListener('change',()=>{state.selected=$$('[name=service]:checked').map(i=>i.value);update();}));
$$('[data-zone]').forEach(b=>b.addEventListener('click',()=>{state.zone=b.dataset.zone;if(!state.selected.includes('film')){state.selected.push('film');$('[name=service][value=film]').checked=true;}update();}));
$('#paint-comparison').addEventListener('input',e=>{const split=Number(e.target.value);$('.compare-frame').style.setProperty('--split',`${split}%`);$('[data-compare-output]').textContent=`${split} / ${100-split}`;});
$('[data-care-book]').addEventListener('click',()=>{const q=careQuote(state);selectBooking(q.rows.length?`${q.rows.map(r=>r.name).join(' + ')} · ${state.size} · ориентир ${money(q.total)}`:'Осмотр автомобиля и подбор ухода');});
initCommon({summary,confirmation:'вариант ухода готов. Это демо: запись в студию не отправлялась. Состав работ можно скачать ниже.'});update();
