import {$,$$,initCommon,selectBooking,downloadText} from './shared.mjs';
import {homeModels,facades,homeQuote,money} from './model.mjs';
import {floorplan} from './floorplan.mjs';
import './homes.css';
let selectedModel=54,state={area:54,facade:'cedar',terrace:true,view:'exterior'},scene;
function summary(){const q=homeQuote(state);return `ХВОЯ ${state.area}\nПлощадь: ${state.area} м²\nСпален: ${homeModels[state.area].bedrooms}\nФасад: ${facades[state.facade].name}\nТерраса: ${q.terraceArea} м²\nДом: ${money(q.base)}\nОтделка: ${money(q.finish)}\nТерраса: ${money(q.deck)}\nИтого: ${money(q.total)}\nДемонстрационный расчёт. Фундамент, доставка и внешние коммуникации не включены.`;}
function update(){const q=homeQuote(state);$$('[data-area]').forEach(b=>b.setAttribute('aria-pressed',String(Number(b.dataset.area)===state.area)));$$('[data-facade]').forEach(b=>b.setAttribute('aria-pressed',String(b.dataset.facade===state.facade)));$('[data-facade-label]').textContent=facades[state.facade].name;$('[data-terrace-area]').textContent=`${state.area/3} м²`;$('[data-home-price]').textContent=money(q.total);$('[data-home-price-detail]').textContent=`Хвоя ${state.area} · ${facades[state.facade].name}${state.terrace?' · с террасой':''}`;$('[data-home-breakdown]').innerHTML=[['Базовый дом',q.base],['Отделка фасада',q.finish],['Терраса',q.deck]].map(([a,b])=>`<div><dt>${a}</dt><dd>${money(b)}</dd></div>`).join('');scene?.update(state);$('[data-home-saved]').textContent='';}
$$('[data-model]').forEach(b=>b.addEventListener('click',()=>{selectedModel=Number(b.dataset.model);const m=homeModels[selectedModel];$$('[data-model]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));$('[data-model-name]').textContent=`Хвоя ${selectedModel}`;$('[data-model-description]').textContent=m.description;$('[data-model-area]').textContent=`${m.area} м²`;$('[data-model-bedrooms]').textContent=m.bedrooms;$('.floor-plan').innerHTML=floorplan(selectedModel);$('[data-use-model]').textContent=`Настроить Хвою ${selectedModel} ↗`;}));
$('[data-use-model]').addEventListener('click',()=>{state.area=selectedModel;update();$('#configurator').scrollIntoView({behavior:matchMedia('(prefers-reduced-motion: reduce)').matches?'instant':'smooth'});});
$$('[data-area]').forEach(b=>b.addEventListener('click',()=>{state.area=Number(b.dataset.area);update();}));
$$('[data-facade]').forEach(b=>b.addEventListener('click',()=>{state.facade=b.dataset.facade;update();}));
$('#terrace').addEventListener('change',e=>{state.terrace=e.target.checked;update();});
$$('[data-view]').forEach(b=>b.addEventListener('click',()=>{state.view=b.dataset.view;$$('[data-view]').forEach(x=>x.setAttribute('aria-pressed',String(x===b)));scene?.setView(state.view);}));
$$('[data-rotate]').forEach(b=>b.addEventListener('click',()=>scene?.rotate(b.dataset.rotate==='left'?-1:1)));
$$('[data-zoom]').forEach(b=>b.addEventListener('click',()=>scene?.zoom(b.dataset.zoom==='in'?1:-1)));
$('[data-camera-reset]').addEventListener('click',()=>scene?.reset());
$('[data-save-home]').addEventListener('click',()=>{downloadText(`Хвоя-${state.area}.txt`,summary());$('[data-home-saved]').textContent='Конфигурация скачана. Можно сохранить ещё один вариант.';});
$('[data-discuss-home]').addEventListener('click',()=>selectBooking(`Хвоя ${state.area} · ${facades[state.facade].name} · ${state.terrace?'с террасой':'без террасы'} · ${money(homeQuote(state).total)}`));
const observer=new IntersectionObserver(async entries=>{if(!entries[0].isIntersecting)return;observer.disconnect();try{const {createHouseScene}=await import('./house-scene.mjs');scene=createHouseScene($('#house-canvas'),state);if(state.view!=='exterior')scene.setView(state.view);$('#house-canvas').dataset.ready='true';}catch(error){console.warn('3D viewer unavailable:',error.message);$('#house-canvas').hidden=true;$('.model-fallback').hidden=false;$$('[data-view],[data-rotate],[data-zoom],[data-camera-reset]').forEach(b=>b.disabled=true);}}, {rootMargin:'500px'});observer.observe($('#house-canvas'));
initCommon({summary,confirmation:'вариант дома собран. Это демо: запрос не отправлялся. Конфигурацию можно скачать и сравнить с другими.'});update();
