<script setup>
import {computed,onBeforeUnmount,ref} from 'vue';import {Gift,Gem,Crown} from 'lucide-vue-next';import {upgradeWins} from './rounds.mjs';
const chosen=ref(0),rotation=ref(0),busy=ref(false),result=ref('');let timer;
const targets=[{name:'Crystal',chance:65,icon:Gem},{name:'Crown',chance:35,icon:Crown}],target=computed(()=>targets[chosen.value]);
function spin(){if(busy.value)return;busy.value=true;result.value='';const angle=Math.random()*360;rotation.value=Math.ceil(rotation.value/360)*360+1080+angle;timer=setTimeout(()=>{result.value=upgradeWins(angle,target.value.chance)?'Апгрейд получился!':'В этот раз не получилось. Попробуйте ещё.';busy.value=false},matchMedia('(prefers-reduced-motion: reduce)').matches?0:2800)}
onBeforeUnmount(()=>clearTimeout(timer));
</script>
<template><div class="upgrade-demo"><div class="upgrade-picks"><div><Gift :size="48"/><span>Gift Box</span></div><div class="upgrade-wheel"><svg viewBox="0 0 200 200" aria-hidden="true"><circle cx="100" cy="100" r="81" fill="none" stroke="#ef4444" stroke-width="5"/><circle cx="100" cy="100" r="81" fill="none" stroke="#9aff27" stroke-width="5" :stroke-dasharray="`${target.chance/100*509} 509`" transform="rotate(-90 100 100)"/><g :style="{transform:`rotate(${rotation}deg)`,transformOrigin:'100px 100px',transition:'transform 2.8s cubic-bezier(.17,.67,.12,.99)'}"><polygon points="100,19 106,42 94,42" fill="white"/></g></svg><strong>{{target.chance}}%</strong></div><div><component :is="target.icon" :size="48"/><span>{{target.name}}</span></div></div><div class="target-picker"><button v-for="(t,i) in targets" :key="t.name" :disabled="busy" :aria-pressed="chosen===i" @click="chosen=i;result=''">{{t.name}} · {{t.chance}}%</button></div><button class="demo-action" :disabled="busy" @click="spin">{{busy?'Улучшаем…':'Попробовать апгрейд'}}</button><p class="demo-status" role="status">{{result||'Выберите цель и запустите вращение.'}}</p></div></template>
<style scoped src="./Upgrade.css"></style>
<style scoped>.upgrade-demo{width:min(100%,550px);margin:auto}.upgrade-picks{display:grid;grid-template-columns:1fr 1.4fr 1fr;align-items:center;gap:10px;padding:50px 0}.upgrade-picks>div:not(.upgrade-wheel){display:flex;flex-direction:column;align-items:center;gap:15px;color:#a1ff44}.upgrade-picks span{font-size:12px;color:white}.upgrade-wheel{position:relative}.upgrade-wheel svg{width:100%;display:block}.upgrade-wheel strong{position:absolute;inset:0;display:grid;place-items:center;font-size:28px;color:#9aff27}.target-picker{display:flex;justify-content:center;gap:10px;margin-bottom:30px}.target-picker button{background:transparent;color:#ddd;border:1px solid #ffffff20;padding:10px;border-radius:8px;font-size:12px}.target-picker button[aria-pressed=true]{border-color:#9aff27;color:#9aff27}.demo-action{width:100%;color:#152308}</style>
