<script setup>
import {defineAsyncComponent,nextTick,ref} from 'vue';import {Gift,Check,RotateCw} from 'lucide-vue-next';import LoyaltyCard from './components/LoyaltyCard.vue';import QrCode from './components/QrCode.vue';
defineProps({compact:Boolean});const StackDemo=defineAsyncComponent(()=>import('./StackDemo.vue'));
const tab=ref('card'),checked=ref(false),qr=ref(false),closeQr=ref();
const balance={available:'1240',pending:'120',held:'0'},profile={customerId:'demo',displayName:'Алексей',membershipId:'demo',phoneMasked:'+7 ••• ••• 1200'},card={id:'demo',serialNumber:'DEMO',alternateText:'Демонстрационная карта',wallets:{appleUrl:null,googleUrl:null},cardTypeName:'Карта участника',qrValue:'LANCER-PORTFOLIO-DEMO-12K'};
async function openQr(){qr.value=true;await nextTick();closeQr.value?.focus()}
</script>
<template><div class="loyalty-demo" :class="{compact}"><header class="demo-topbar"><span class="demo-wordmark">12К <small>Клуб привилегий</small></span><small>Демо участника</small></header><nav v-if="!compact" class="demo-tabs" aria-label="Раздел 12К"><button :aria-pressed="tab==='card'" @click="tab='card'">Моя карта</button><button :aria-pressed="tab==='stack'" @click="tab='stack'">Играть в Stack</button><button :aria-pressed="tab==='dashboard'" @click="tab='dashboard'">Кабинет бизнеса</button></nav>
 <div v-if="tab==='card'" class="card-scene"><div v-if="qr" class="qr-expanded"><QrCode :value="card.qrValue" :size="200"/><p>Демонстрационная карта</p><button ref="closeQr" class="demo-action" @click="qr=false">Вернуться к карте</button></div><template v-else><div class="card-wrap"><LoyaltyCard :balance="balance" :card="card" :profile="profile" @open-qr="openQr"/></div><p class="flip-invitation"><RotateCw :size="13"/> Нажмите на карту — на обороте QR-код</p><button class="daily-demo" :disabled="checked" @click="checked=true"><span><component :is="checked?Check:Gift" :size="23"/><span><b>{{checked?'Бонус получен':'Бонус за сегодня'}}</b><small>{{checked?'Завтра будет новый повод вернуться':'Отметьтесь и продолжите серию'}}</small></span></span><strong>{{checked?'✓':'+25'}}</strong></button></template></div>
 <StackDemo v-else-if="tab==='stack'"/><div v-else class="dashboard-demo"><span>Покупки, участники и начисления</span><button type="button" class="dashboard-capture" data-zoom="/assets/screenshots/12k-dashboard.webp" data-caption="12К — кабинет бизнеса" aria-label="Увеличить кабинет бизнеса"><img src="/assets/screenshots/12k-dashboard.webp" alt="Реальный интерфейс кабинета 12К"/></button><p>Актуальный интерфейс · демонстрационные показатели</p></div><p v-if="!compact" class="demo-note">Карта и игровое поле — компоненты 12К Mini App</p></div></template>
<style scoped>.loyalty-demo{--demo-accent:#0075ce;background:#090e13;color:#eef5f9;padding:28px 38px;border-radius:24px;min-height:590px}.demo-wordmark{font-size:28px;letter-spacing:-1.8px}.demo-wordmark small{font-size:9px;letter-spacing:0;display:inline-block;margin-left:12px}.card-scene{max-width:420px;margin:auto}.card-wrap{max-width:410px;margin:10px auto 0}.flip-invitation{display:flex;gap:7px;justify-content:center;align-items:center;color:#87a3b7;font-size:10px;margin:18px 0!important}.daily-demo{width:100%;background:#102332;border:1px solid #1b415c;color:#e5f4ff;border-radius:14px;padding:18px;text-align:left;display:flex;align-items:center;justify-content:space-between;gap:15px}.daily-demo>span{display:flex;align-items:center;gap:12px}.daily-demo small{display:block;color:#88a5b8;font-size:10px;margin-top:5px}.daily-demo b{font-size:14px}.daily-demo>strong{font-size:25px;color:#279cff}.qr-expanded{display:flex;flex-direction:column;align-items:center;gap:20px;padding:15px}.dashboard-demo>span{display:block;font-size:18px;margin:10px 0 20px}.dashboard-capture{width:100%;padding:0;border:0;background:none;border-radius:12px;overflow:hidden}.dashboard-capture img{width:100%;display:block}.dashboard-demo>p{font-size:11px;color:#91a3b0;margin-top:14px}.compact{height:390px;min-height:0;padding:22px 26px}.compact .card-scene{max-width:320px}.compact .card-wrap{max-width:300px;margin:0 auto}.compact .daily-demo{padding:12px}.compact .daily-demo b{font-size:12px}.compact .daily-demo small{font-size:9px}.compact .flip-invitation{margin:12px 0!important;font-size:9px}.compact .qr-expanded{padding:0}.compact .qr-expanded :deep(.qr-code svg){width:150px;height:150px}@media(max-width:600px){.loyalty-demo{padding:22px 16px}.demo-wordmark small{display:none}.compact .card-wrap{max-width:280px}.daily-demo{padding:14px}}</style>
