<script setup>
import {onBeforeUnmount,onMounted,ref} from 'vue';import StackCanvas from './components/StackCanvas.vue';
const rules={rulesVersion:1,baseSizeMilli:3000,minOverlapMilli:120,perfectToleranceMilli:90,movementRangeMilli:4200,initialSpeedMilliPerSecond:1800,speedStepMilliPerSecond:85,maxSpeedMilliPerSecond:3200,minEventIntervalMs:180,maxEventIntervalMs:15000,runTtlSeconds:300,maxEvents:100};
const running=ref(false),runId=ref(null),seed=ref(1),count=ref(0),message=ref('Останавливайте блоки друг над другом.'),root=ref();let observer;
function start(){count.value=0;seed.value=Math.floor(Math.random()*100000);runId.value=crypto.randomUUID();running.value=true;message.value='Нажимайте на поле или используйте пробел.'}
function place(state){count.value=state.blocks.filter(block=>!block.isMiss).length;if(state.blocks.at(-1)?.isPerfect)message.value='Идеально! Размер блока сохранён.';else message.value='Следующий блок — по другой оси.'}
function ended(){running.value=false;message.value=`Башня: ${count.value} блоков. Попробуем ещё?`}
onMounted(()=>{observer=new IntersectionObserver(([entry])=>{if(!entry.isIntersecting&&running.value){running.value=false;message.value='Раунд остановлен. Можно начать заново.'}});observer.observe(root.value)});onBeforeUnmount(()=>observer?.disconnect());
</script>
<template><div ref="root" class="stack-demo"><div class="stack-box"><StackCanvas :rules="rules" :run-id="runId" :seed="seed" :running="running" @place="place" @ended="ended" @timeout="ended"/><div class="stack-counter" aria-live="polite">{{count}}<span>БЛОКОВ</span></div><div v-if="!running" class="stack-overlay"><strong>{{runId?'Ещё выше?':'STACK'}}</strong><button class="demo-action" @click="start">{{runId?'Играть снова':'Построить башню'}}</button></div></div><p id="stack-control-help" class="demo-status" role="status">{{message}}</p></div></template>
<style scoped>.stack-box{height:390px;position:relative;border-radius:16px;overflow:hidden;background:#050505}.stack-counter{position:absolute;top:20px;left:25px;font-size:44px;color:white;pointer-events:none;line-height:1}.stack-counter span{display:block;font-size:9px;letter-spacing:.18em;margin-top:8px;color:#999}.stack-overlay{position:absolute;inset:0;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:25px;background:#05050545}.stack-overlay>strong{font-size:50px;font-weight:800;letter-spacing:.08em;color:#fff}.stack-overlay button{z-index:3}.demo-status{color:#abc3d2}@media(max-width:600px){.stack-box{height:340px}}</style>
