<script setup>
import {nextTick,onBeforeUnmount,onMounted,ref} from 'vue';import {Star,KeyRound,Trophy} from 'lucide-vue-next';
import {buildRouletteIdleStrip,buildRouletteSpinStrip,calculateCenteredTranslate} from './rouletteStrip';
defineProps({compact:Boolean});
const prizes=[100,250,500,1000].map(n=>({id:String(n),title:`${n} баллов`,points_value:n}));
const plan=ref(buildRouletteIdleStrip(prizes)),position=ref(0),busy=ref(false),balance=ref(1250),message=ref('Ключи для демо не заканчиваются.'),windowEl=ref(),trackEl=ref(),tab=ref('roulette');let animation,observer;
function center(key){const el=[...trackEl.value.children].find(el=>el.dataset.cellKey===key);return el?calculateCenteredTranslate({cellLeft:el.offsetLeft,cellWidth:el.offsetWidth,containerWidth:windowEl.value.clientWidth}):0}
async function spin(){if(busy.value)return;busy.value=true;message.value='Лента выбирает награду…';const target=prizes[Math.floor(Math.random()*prizes.length)];plan.value=buildRouletteSpinStrip({visiblePrizes:prizes,targetPrize:target});await nextTick();const from=center(plan.value.anchorCellKey),to=center(plan.value.targetCellKey);position.value=from;animation=trackEl.value.animate([{transform:`translateX(${from}px)`},{transform:`translateX(${to}px)`}],{duration:matchMedia('(prefers-reduced-motion: reduce)').matches?0:3500,easing:'cubic-bezier(.12,.75,.18,1)',fill:'forwards'});animation.onfinish=()=>{position.value=to;balance.value+=target.points_value;message.value=`+${target.points_value} демо-баллов. Награда добавлена в профиль.`;busy.value=false;animation.cancel()}}
onMounted(()=>{position.value=center(plan.value.anchorCellKey);observer=new ResizeObserver(()=>{if(!busy.value)position.value=center(plan.value.targetCellKey)});observer.observe(windowEl.value)});onBeforeUnmount(()=>{animation?.cancel();observer?.disconnect()});
</script>
<template><div class="maverick-demo" :class="{compact}"><header class="demo-topbar"><span class="demo-wordmark">MAVERICK</span><span class="member-balance"><Star :size="14"/>{{balance.toLocaleString('ru-RU')}}</span></header><nav v-if="!compact" class="demo-tabs" aria-label="Раздел Maverick"><button :aria-pressed="tab==='roulette'" :disabled="busy" @click="tab='roulette'">Рулетка</button><button :aria-pressed="tab==='profile'" :disabled="busy" @click="tab='profile'">Профиль участника</button></nav>
 <div v-show="tab==='roulette'" class="roulette-content"><div class="roulette-heading"><span>Бегущая дорожка</span><h3>Крути. Собирай. Возвращайся.</h3></div><section class="mav-wood-card mav-roulette-machine" aria-label="Рулетка призов"><div class="mav-roulette-arch"><Star :size="17"/><strong>Испытай удачу</strong></div><div ref="windowEl" class="mav-strip-window"><div ref="trackEl" class="mav-strip-track" :style="{transform:`translateX(${position}px)`}"><article v-for="cell in plan.cells" :key="cell.cellKey" class="mav-prize-cell" :data-cell-key="cell.cellKey" :data-jackpot="cell.points_value>=1000" :data-target="cell.isTarget"><Star :size="23" fill="#c7a348" color="#c7a348"/><strong>+{{cell.points_value}}</strong><small>баллов</small></article></div><div class="mav-strip-fade mav-strip-fade--left"></div><div class="mav-strip-fade mav-strip-fade--right"></div><div class="mav-strip-pointer" aria-hidden="true"></div></div></section><button class="demo-action" :disabled="busy" @click="spin"><KeyRound :size="17"/>{{busy?'Крутим…':'Крутить рулетку'}}</button><p class="demo-status" role="status">{{message}}</p></div>
 <div v-if="tab==='profile'" class="member-profile"><div class="member-avatar">А</div><span>Участник сообщества</span><h3>Алексей</h3><strong>{{balance.toLocaleString('ru-RU')}} <small>баллов</small></strong><div class="member-achievements"><span><Trophy/>Первый шаг</span><span><Star/>Коллекционер</span><span><KeyRound/>Исследователь</span></div><p>Покрутите рулетку — баланс обновится здесь.</p></div>
 <p class="demo-note">Демо-профиль · баллы сохраняются только до обновления страницы</p></div></template>
<style scoped src="./reel.css"></style>
<style scoped>
.maverick-demo{--demo-accent:#d50c2d;--mav-gold:#c7a348;--mav-wood-3:#6e4c29;--mav-border:#d5c4a6;--mav-paper:#fff7e7;--mav-blue:#171467;--mav-red:#df1835;--mav-muted:#887951;background:#f2e7d6;color:#171b31;padding:28px 38px;border-radius:24px;min-height:590px}.demo-wordmark{letter-spacing:.03em;font-style:italic;font-size:23px;color:#171467}.member-balance{display:flex;gap:7px;align-items:center;padding:6px 12px;background:#171467;color:#f4d175;border-radius:8px;font-size:13px;font-weight:700}.roulette-content{max-width:500px;margin:auto}.roulette-heading{text-align:center;margin:4px 0 50px}.roulette-heading>span{font-size:10px;text-transform:uppercase;letter-spacing:.18em;color:#8a704e}.roulette-heading h3{font-size:25px;margin-top:6px}.mav-wood-card{background:repeating-linear-gradient(0deg,#654525 0 24px,#5d3d1e 25px 27px);border:1px solid #805937}.mav-roulette-arch{color:#f4d175}.demo-action{width:100%;margin-top:18px}.member-profile{display:flex;align-items:center;flex-direction:column;gap:12px;text-align:center;padding:20px}.member-avatar{display:grid;place-items:center;width:80px;height:80px;background:#171467;color:white;font-size:40px;border-radius:50%}.member-profile>strong{font-size:45px}.member-profile>strong small{font-size:14px}.member-achievements{display:flex;justify-content:center;gap:12px;margin:10px 0}.member-achievements span{display:flex;flex-direction:column;align-items:center;font-size:10px;gap:12px;padding:15px;background:#ffffff75;border-radius:10px}.member-achievements svg{color:#b68b2c}.member-profile p{font-size:12px}.compact{height:390px;min-height:0;padding:22px 26px}.compact .roulette-heading{margin:0 0 30px}.compact .roulette-heading h3{font-size:18px}.compact .roulette-heading>span{font-size:8px}.compact .mav-roulette-arch{height:42px}.compact .mav-roulette-arch:before{height:68px}.compact .mav-roulette-machine{padding-bottom:10px}.compact .mav-strip-window{margin-top:10px;height:92px}.compact .mav-prize-cell{height:72px;width:72px;gap:4px}.compact .mav-prize-cell strong{font-size:15px}.compact .mav-strip-track{top:8px}.compact .demo-action{margin-top:12px}@media(max-width:600px){.maverick-demo{padding:22px 16px}.roulette-heading h3{font-size:21px}.compact{padding:22px 20px}.member-achievements{gap:5px}}
</style>
