import {head,nav,rail,icon,arrow,cta,phone,desktop,footer} from './agency-shared.mjs';
const serviceData=[['Сайты и лендинги','Создаём сайты, которые работают на ваш бизнес.','Сайт'],['Telegram Mini Apps','Интерактивные сервисы в Telegram, от идеи до запуска.','Mini App'],['CRM и админ-панели','Удобные системы для управления бизнесом и командой.','CRM'],['Автоматизация','Объединяем сервисы и процессы в единую экосистему.','Автоматизация']];
export function home(){return head('Сложные идеи. Удобные продукты.','Разрабатываем сайты, Telegram Mini Apps и системы для бизнеса. Lancer Agency — от идеи и дизайна до запуска продукта.')+nav()+`<main id="main">
<section class="hero scene" aria-labelledby="hero-title">${rail()}<div class="hero-copy"><span class="eyebrow">Разрабатываем цифровые решения</span><h1 id="hero-title">Сложные идеи.<br>Удобные продукты.</h1><p>Сайты, Telegram Mini Apps и системы для бизнеса.</p><div class="actions">${cta()}<a class="text-link" href="#works">Смотреть кейсы ${arrow}</a></div></div>
<div class="hero-glass-copy" aria-hidden="true"><b>LANCER</b><span>Идея<br><i>↓</i><br>Продукт</span></div><div class="hero-tags glass" aria-hidden="true"><span>◉ &nbsp; Понимаем</span><span>◉ &nbsp; Проектируем</span><span>◉ &nbsp; Разрабатываем</span><span>◉ &nbsp; Запускаем</span></div>
<div class="hero-note glass"><span class="status-dot"></span><span>Технологии<br>для реальных задач.</span></div><div class="hero-previews"><a class="hero-preview glass" href="/cases/maverick/"><b>Mini App</b><small>Программа лояльности</small>${arrow}<img src="/assets/screenshots/club-home.webp" alt="Интерфейс Maverick" width="390" height="844"></a><a class="hero-preview glass automation-preview" href="#ecosystem"><b>Автоматизация</b><small>Бизнес-процессы</small>${arrow}<span class="mini-network"><i>${icon('people')}</i><i>${icon('bolt')}</i><i>${icon('settings')}</i></span></a></div></section>
<section class="services wrap" id="services"><div class="section-heading"><div><span class="eyebrow">Что мы делаем</span><h2>Что создаём</h2></div><p>Помогаем бизнесу расти —<br>с помощью современных технологий<br>и понятных решений.</p><span class="side-note">Бизнес, которым<br>удобно управлять</span></div><div class="service-grid">${serviceData.map(([title,desc],i)=>`<a class="service" href="https://t.me/landlancer" target="_blank" rel="noopener noreferrer"><div class="service-art art-${i}" aria-hidden="true"></div><h3>${title}</h3><p>${desc}</p>${arrow}</a>`).join('')}</div>
<div class="custom glass"><div class="custom-copy"><span class="custom-icon">${icon('code')}</span><div><h3>Заказная разработка</h3><p>MVP для стартапов и сервисы под вашу задачу.<br>Без лишних решений — только результат.</p></div>${cta('Обсудить идею')}</div><div class="code-object glass" aria-hidden="true">${icon('code')}</div><ol class="process-list glass"><li>Идея</li><li>MVP</li><li>Разработка</li><li>Результат</li></ol></div></section>
<section class="ecosystem scene" id="ecosystem"><div class="section-heading"><div><span class="eyebrow">Единая экосистема</span><h2>Всё работает вместе</h2><p>Соединяем сайт, бота и внутренние процессы<br>в одну систему.</p></div><span class="side-note">Любая сложность.<br>Для вашего бизнеса.</span></div><div class="ecosystem-composition"><div class="system-stack">${serviceData.map(([,],i)=>`<div class="glass stack-layer"><span class="glass-icon">${icon(['home','telegram','layers','settings'][i])}</span>${['Сайт','Telegram Mini App','CRM и база клиентов','Автоматизация'][i]}</div>`).join('')}</div><div class="system-panels"><div class="glass system-panel"><b>Заявки</b><span><i class="avatar">А</i> Новая заявка <em>Принята</em></span><span><i class="avatar">М</i> Консультация <em>В работе</em></span><span><i class="avatar">Д</i> Новый проект <em>Обсуждаем</em></span></div><div class="glass system-panel compact"><b>Команда</b><span><i class="avatar">А</i> Дизайнер</span><span><i class="avatar">М</i> Разработчик</span><span><i class="avatar">К</i> Менеджер</span></div><div class="glass system-panel notifications"><b>Уведомления</b><span>${icon('chat')} Новая заявка с сайта <small>только что</small></span><span>${icon('telegram')} Пользователь в Mini App <small>1 мин назад</small></span><span>${icon('layers')} Задача в CRM <small>2 мин назад</small></span></div></div></div><span class="handwritten">Всё<br>имеет связь</span><small class="scene-caption">Иллюстрация возможной системы</small></section>
<section class="works wrap" id="works"><div class="section-heading"><div><span class="eyebrow">Наши работы</span><h2>Избранные проекты</h2></div><span class="side-note">У каждого продукта —<br>свой характер</span></div><div class="project-grid">
<a class="project-card project-maverick" href="/cases/maverick/"><div class="project-cover"><h3>Бонусы<br>стали ближе</h3><div class="cover-phone"><img src="/assets/screenshots/club-home.webp" alt="Главный экран Maverick" width="390" height="844" loading="lazy"></div><span class="cover-orbit"></span></div><div class="project-caption glass"><div><b>Maverick</b><small>Mini App · Программа лояльности</small></div>${arrow}</div></a>
<a class="project-card project-gift" href="/cases/gift-roulette/"><div class="project-cover"><h3>Целый мир<br>в Telegram</h3><div class="cover-phone"><img src="/assets/screenshots/gaming-case.webp" alt="Интерфейс Gift Roulette" width="390" height="844" loading="lazy"></div></div><div class="project-caption glass"><div><b>Gift Roulette</b><small>Telegram · Игровая платформа</small></div>${arrow}</div></a>
<a class="project-card project-tailcare" href="/cases/tailcare/"><div class="project-cover"><h3>Помогаем<br>найти друг друга</h3><div class="cover-browser"><img src="/assets/screenshots/pets-home.webp" alt="Главная TailCare" width="1440" height="1000" loading="lazy"></div></div><div class="project-caption glass"><div><b>TailCare</b><small>Веб-сервис · Помощь питомцам</small></div>${arrow}</div></a>
<article class="project-card project-loyalty"><div class="project-cover"><h3>Больше поводов<br>вернуться</h3><div class="loyalty-art glass" aria-hidden="true"><span>12K</span><b>Ваши привилегии</b><i></i><small>MINI APP + LOYALTY API</small></div><span class="wip glass"><i class="status-dot"></i> В разработке</span></div><div class="project-caption glass"><div><b>12K Mini App + Loyalty API</b><small>Единая система лояльности · Кейс скоро</small></div><span class="soon">Скоро</span></div></article></div></section>
<section class="approach scene" id="approach"><div class="section-heading"><div><span class="eyebrow">Как мы работаем</span><h2>Как мы работаем</h2><p>Собираем команду под задачу.</p></div></div><div class="team-grid">${[['people','Менеджер проекта','Понимает вашу задачу. Ведёт проект от идеи до запуска.'],['code','Техлид','Проектирует архитектуру. Помогает принять верные решения.'],['leaf','Дизайнер','Продумывает сценарии. Создаёт понятный интерфейс.'],['layers','Разработчики','Собирают продукт. Соединяют интерфейс и логику.'],['shield','QA-инженер','Проверяет сценарии. Помогает избежать ошибок.']].map(([i,t,d])=>`<article class="team-card glass"><span class="glass-icon">${icon(i)}</span><div><h3>${t}</h3><p>${d}</p></div></article>`).join('')}</div><span class="progress-pill glass"><span class="status-dot"></span>Вы видите прогресс на каждом этапе</span></section>
</main>`+footer();}
