import {faqBlock} from './seo.mjs';
import {services} from './seo-data.mjs';
import {projectCover} from './project-cover.mjs';
import {head,icon,cta,footer} from './agency-shared.mjs';
const projects=[['maverick','Maverick'],['loyalty','12К · Программа лояльности'],['gift-roulette','Gift Roulette'],['tailcare','TailCare']];
const stages=[
 ['Разбираемся в задаче','Обсуждаем пользователей, сценарии и ограничения. Отделяем необходимое для запуска от идей на будущее.','Обсуждаем вместе','Задачи пользователей, приоритеты и границы первой версии.','План работ и согласованный состав MVP.',['Сценарии','Приоритеты','Состав MVP']],
 ['Проектируем интерфейс','Сначала собираем логику экранов, затем — визуальный язык. Мобильную версию продумываем вместе с основной.','Показываем прототип','Проходим ключевой сценарий в кликабельном макете до разработки.','Согласованные макеты и состояния интерфейса.',['Структура','Прототип','Дизайн']],
 ['Собираем продукт','Разрабатываем интерфейс, серверную логику и интеграции. Показываем законченные сценарии по мере готовности.','Демонстрируем сборку','Проверяем на тестовом стенде реальные действия пользователя.','Работающая версия продукта для проверки.',['Интерфейс','Бэкенд','Интеграции']],
 ['Проверяем и дорабатываем','Проверяем формы, права доступа, мобильные экраны и ошибки. Собираем замечания и повторно проходим исправленные сценарии.','Проводим приёмку','Сверяем поведение продукта с согласованными требованиями.','Проверенная версия и согласованные доработки.',['Сценарии','Адаптив','Исправления']],
 ['Запускаем и передаём','Настраиваем публикацию и проверяем продукт на рабочем адресе. Передаём код, доступы и инструкции.','Показываем управление','Разбираем, как пользоваться кабинетом после запуска.','Опубликованный продукт, исходники и документация.',['Публикация','Доступы','Инструкции']]
];
function process(){return `<section class="studio-process studio-section" id="approach"><div class="studio-section-title"><span>Процесс</span><h2>Вы видите результат<br>на каждом этапе.</h2><p>Обсуждаем решения и показываем продукт в работе.</p></div><div class="process-list">${stages.map(([title,desc,label,demo,result,tags],i)=>`<details name="process" ${i===0?'open':''}><summary><h3>${title}</h3><span class="disclosure" aria-hidden="true">+</span></summary><div class="process-content"><p>${desc}</p><div class="process-tags">${tags.map(t=>`<span>${t}</span>`).join('<i aria-hidden="true">→</i>')}</div><div class="process-delivery"><div>${icon('chat')}<strong>${label}</strong><p>${demo}</p></div><div>${icon('check')}<strong>На выходе</strong><p>${result}</p></div></div></div></details>`).join('')}</div></section>`}
export function home(){return head('Сложные идеи. Удобные продукты.','Разрабатываем сайты, Mini Apps и системы для бизнеса. От идеи до запуска — Lancer Agency.').replace('class="theme-blue"','class="theme-blue studio-home"')+`
<header class="studio-header"><a class="studio-brand" href="/" aria-label="Lancer Agency — главная">${icon('layers')}Lancer<span>Agency</span></a><nav aria-label="Основная навигация"><a href="#works">Проекты</a><a href="#services">Услуги</a><a href="#approach">Процесс</a></nav>${cta()}</header>
<main id="main" class="studio-main"><section class="studio-hero" id="about"><div><span class="studio-kicker">Дизайн · Разработка · Интеграции</span><h1>Сложные идеи.<br><span>Удобные продукты.</span></h1></div><div class="studio-hero-note"><p>Создаём сайты, Telegram Mini Apps<br>и рабочие системы для бизнеса.</p><p>От первого сценария до запуска.<br>С вниманием к каждой детали.</p><a href="#works">Посмотреть работы ${icon('arrow')}</a></div></section>
<section class="studio-works" id="works"><div class="studio-work-heading"><h2>Избранные проекты</h2><span>Интерфейсы, которыми можно пользоваться</span></div><div class="studio-projects">${projects.map(([slug,name])=>`<article class="studio-project" id="project-${slug}">${projectCover(slug,name)}</article>`).join('')}</div></section>
<section class="studio-services studio-section" id="services"><div class="studio-section-title"><span>Услуги</span><h2>Под вашу задачу.<br>До рабочего продукта.</h2><p>Можно начать с первой версии или подключиться к развитию существующего продукта.</p>${cta('Обсудить задачу')}</div><div class="studio-service-list">${services.map((s,i)=>`<a href="/services/${s.slug}/"><span class="service-symbol">${icon(['home','telegram','layers','settings'][i])}</span><div><h3>${s.name}</h3><p>${['Лендинги, каталоги и веб-сервисы. От структуры страниц до заявок и аналитики.','Продукт внутри Telegram: личный кабинет, покупки, бонусы и игровые сценарии.','Клиенты, операции и отчёты в одном интерфейсе. Доступы под разные роли.','Связываем сайт, Telegram и CRM. Автоматизируем повторяющиеся действия.'][i]}</p></div>${icon('arrow')}</a>`).join('')}</div></section>${process()}${faqBlock()}</main>`+footer();}
