import {productStage} from './product-stage.mjs';
import {head,nav,rail,icon,arrow,cta,phone,desktop,footer} from './agency-shared.mjs';
export const cases=[
 {slug:'gift-roulette',name:'Gift Roulette',theme:'gift',type:'Telegram Mini App',intro:'Четыре игровых интерфейса, личный кабинет и управление через Telegram.',tags:['Интерфейс','Backend','Telegram-бот'],screens:['gift-mines-active.webp','gaming-case.webp'],hand:'Дарим<br>возможности',section:'Один продукт — четыре игровых режима',sub:'Разные сценарии взаимодействия, общий профиль и единая навигация.',features:[
 ['Кейсы','Каталог предметов и анимированная лента. Отдельный экран результата.','Коллекционные предметы со всего мира Telegram','gaming-case.webp','gift'],
 ['Мины','Интерактивное поле 5 × 5. Визуальные состояния ячеек и обновление интерфейса в ходе раунда.','Продуманная механика и чистый интерфейс','gift-mines-current.webp','grid'],
 ['Апгрейд','Выбор двух предметов, круговой индикатор и анимация результата.','Визуальная обратная связь в реальном времени','gift-upgrade-current.webp','arrow'],
 ['Краш','График в реальном времени, история раундов и синхронизация через WebSocket.','Динамичные раунды и синхронизация с сервером','gift-crash-active.webp','chart']
 ],extraTitle:'Больше, чем игровые экраны',extra:[['people','Личный кабинет','Профиль, настройки и история'],['check','Задания','Список активностей и прогресс'],['gift','Инвентарь','Каталог цифровых предметов'],['settings','Управление','Пользователи, контент и рассылки в Telegram']],extraHand:'Единая<br>экосистема<br>в Telegram',details:[['Единый профиль','Баланс, коллекция подарков, история действий и реферальная программа связаны с одним Telegram-аккаунтом.'],['Серверная логика','Интерфейс показывает подтверждённые сервером результаты. База данных хранит пользователей, предметы и операции.'],['Инструменты оператора','Управление кейсами, призами, заданиями и рассылками через Telegram. Статистика помогает видеть работу продукта.']],stack:[['V','Vue 3','Фронтенд'],['ϟ','FastAPI','Бэкенд'],['telegram','aiogram 3','Telegram-бот'],['layers','PostgreSQL','База данных']],infra:'Docker · nginx · WebSocket',note:'Настоящие интерфейсы Gift Roulette: игровые сценарии и дополнительные экраны приложения.'},
 {slug:'maverick',name:'Maverick',theme:'maverick',type:'Программа лояльности',intro:'От QR-кода на продукте до баллов, достижений и собственного магазина мерча.',tags:['Telegram Mini App','Веб-админка','Интеграции'],screens:['club-home.webp','club-roulette.webp'],hand:'Повод<br>вернуться',section:'Каждый контакт становится частью истории',sub:'Активация, вовлечение и награды — в одном приложении бренда.',features:[
 ['Покупка становится началом','Сканирование QR-кода камерой Telegram или ручной ввод. После активации баллы появляются в личном кабинете.','Один QR-код — одна активация','club-home.webp','shield'],
 ['Награды за участие','Ключи открывают доступ к рулетке. Каталог наград и результаты связаны с балансом участника.','Понятный путь от действия к награде','club-roulette.webp','gift'],
 ['Причина заходить снова','Ежедневные задания, серии посещений, достижения и игровые рейтинги поддерживают регулярное взаимодействие.','Прогресс виден прямо в приложении','club-tasks.webp','chart'],
 ['Магазин внутри Mini App','Каталог мерча, оформление заказов за баллы и статусы. Остатки и товары синхронизируются с МойСклад.','От выбора до получения','club-shop.webp','layers']
 ],extraTitle:'Одна система для бренда и участников',extra:[['shield','QR-активация','Одноразовые коды и история начислений'],['people','Вовлечение','Задания, достижения и рефералы'],['gift','Магазин','Мерч, заказы и остатки'],['settings','Веб-админка','Контент, рассылки и аналитика']],extraHand:'Ближе<br>к своему<br>сообществу',details:[['Учёт баллов','Каждое начисление и списание сохраняется в истории. Ключи для рулетки учитываются отдельно от баллов.'],['Управление программой','Веб-панель объединяет работу с участниками, кодами, наградами, заказами и контентом. Рассылки отправляются через Telegram-бота.'],['Интеграции','МойСклад связывает товары и остатки с магазином. Фоновые задачи обрабатывают синхронизацию и уведомления.']],stack:[['V','Vue 3','Mini App + админка'],['ϟ','FastAPI','Серверная логика'],['telegram','aiogram','Telegram-бот'],['layers','PostgreSQL','Учёт операций']],infra:'Redis · Celery · МойСклад · Docker',note:'Настоящие экраны Maverick. Баланс, задания и каталог показаны на демонстрационных данных.'},
 {slug:'tailcare',name:'TailCare',theme:'tailcare',type:'Сервис помощи питомцам',intro:'Помогаем потерявшимся питомцам вернуться домой, а людям — найти нового друга.',tags:['Веб-сервис','Каталог','Telegram-бот'],screens:['pets-home.webp','pets-catalog.webp'],hand:'Чтобы каждый<br>нашёл свой дом',section:'Забота начинается с понятного действия',sub:'Потерял, нашёл, хочу помочь — для каждой ситуации свой короткий путь.',features:[
 ['Один понятный вход','Главная помогает сразу выбрать свою ситуацию: найти питомца, сообщить о найденном или помочь приюту.','В тревожный момент важна ясность','pets-home.webp','home'],
 ['Питомцы рядом','Каталог с фотографиями, категориями и фильтрами. Город и район помогают сузить поиск.','Нужное объявление — без лишних шагов','pets-catalog.webp','pin'],
 ['Помощь объединяет','Отдельный раздел для волонтёров и организаций. Профили, контакты и информация о том, какая помощь нужна.','Место для тех, кто не остаётся в стороне','pets-volunteers.webp','people']
 ],extraTitle:'Сайт, люди и Telegram связаны',extra:[['chat','Публикация','Создание объявлений через бота'],['shield','Модерация','Проверка перед публикацией'],['pin','География','Город, район и координаты'],['people','Сообщество','Приюты, волонтёры и владельцы']],extraHand:'Помогаем<br>найти<br>друг друга',details:[['Объявление начинается в Telegram','Бот последовательно собирает описание, фотографии и местоположение. После проверки карточка появляется в публичном каталоге.'],['Контекст вместо лишних действий','В подробной карточке собраны сведения о питомце, фотографии и контакты. Координаты можно открыть во внешних картах.'],['Поддержка сообщества','Профили волонтёров и организаций помогают найти поддержку. Для организаций предусмотрена информация о помощи и реквизиты пожертвований.']],stack:[['V','Vue 3','Веб-интерфейс'],['ϟ','FastAPI','REST API'],['telegram','Telegram','Публикация и модерация'],['layers','SQLAlchemy','Работа с данными']],infra:'Адаптивная вёрстка · REST API · Telegram',note:'Настоящие экраны TailCare с демонстрационными объявлениями.'}
];
cases.push({slug:'loyalty',name:'12К',theme:'loyalty',type:'Единая программа лояльности',intro:'Mini App для участников и рабочий кабинет для бизнеса. Покупки, бонусы, задания и коммуникации — в одной системе.',tags:['Telegram Mini App','Кабинет бизнеса','Loyalty API'],screens:['12k-home.webp','12k-dashboard.webp'],hand:'Каждая покупка.<br>Новая связь.',section:'От карты участника до управления бизнесом',sub:'Два интерфейса. Один связанный продукт.',features:[
 ['Карта всегда под рукой','Личная карта с QR-кодом и рублёвым кэшбэком. Быстрый доступ к магазину, играм и адресам точек.','Баланс и карта в одном экране','12k-home.webp','shield'],
 ['Повод вернуться','Ежедневные задания, опросы и достижения. Баллы активности учитываются отдельно от кэшбэка с покупок.','Понятный прогресс участника','12k-missions.webp','chart'],
 ['Награды внутри приложения','Каталог мерча, корзина и оформление доставки. Для каждого предложения видны стоимость и доступность.','От активности — к награде','12k-shop.webp','gift'],
 ['Бизнес видит всю картину','Финансовые результаты, средний чек, активность базы и история операций. Отдельные разделы для клиентов, рассылок и правил программы.','Единый кабинет управления','12k-dashboard.webp','layers']
 ],extraTitle:'Лояльность как часть вашего бизнеса',extra:[['people','Клиенты и сегменты','Профили, группы и история покупок'],['chart','Аналитика','Показатели продаж и активности'],['chat','Коммуникации','Рассылки, события и обратная связь'],['settings','Интеграции','ЭВОТОР, API и webhooks']],details:[['Две самостоятельные валюты','Рублёвый кэшбэк начисляется за подтверждённые покупки. Баллы активности — за задания и другие действия внутри Mini App. Балансы не смешиваются.'],['Один кабинет для команды','Рабочее пространство объединяет клиентскую базу, правила лояльности, аналитику и коммуникации. Права сотрудников определяют доступ к разделам.'],['Связь с кассой и сервисами','Loyalty API обрабатывает операции программы. Для ЭВОТОР предусмотрено отдельное приложение. SMS и Wallet требуют настройки соответствующих провайдеров.']],stack:[['V','Vue 3','Telegram Mini App'],['layers','Nuxt 4','Кабинет бизнеса'],['ϟ','FastAPI','Серверная логика'],['layers','PostgreSQL','Данные и операции']],infra:'Telegram · ЭВОТОР · API · Webhooks',note:'Актуальные интерфейсы 12К сняты 23 сентября 2026 года. Данные участника и показатели бизнеса — демонстрационные.'});
function screen(p,file,extra='') {const wide=p.theme==='tailcare'||file.includes('dashboard');return wide?desktop(file,`${p.name}: ${p.features.find(f=>f[3]===file)?.[0]||'интерфейс'}`,extra):phone(file,`${p.name}: ${p.features.find(f=>f[3]===file)?.[0]||'интерфейс'}`,extra)}
function extraGallery(p){return p.theme==='gift'?`<details class="extra-screens"><summary>Другие экраны приложения <span>+</span></summary><div class="extra-screen-grid">${[['gaming-home.webp','Выбор игры'],['gaming-mines.webp','Поле мин'],['gaming-upgrade.webp','Выбор предметов'],['gaming-crash.webp','Ожидание раунда']].map(([file,label])=>`<figure>${phone(file,`Gift Roulette: ${label}`)}<figcaption>${label}</figcaption></figure>`).join('')}</div></details>`:''}
export function casePage(p){return head(`${p.name} — ${p.type}`,p.intro,`/cases/${p.slug}/`,p.theme)+`<main id="main"><div class="case-shell scene">${nav(true)}<section class="case-hero" id="overview">${rail()}<div class="case-intro"><span class="eyebrow">Кейс проекта</span><h1>${p.name}</h1><h2>${p.type}</h2><p>${p.intro}</p><div class="tags">${p.tags.map(t=>`<span class="glass">${t}</span>`).join('')}</div></div>${productStage(p)}<div class="case-hero-bottom"><span class="case-note glass"><i class="status-dot"></i> ${p.theme==='tailcare'?'Помогаем найти друг друга':p.theme==='gift'?'Четыре режима. Один продукт.':p.theme==='loyalty'?'Для участников и для бизнеса':'Ближе к своему сообществу'}</span><a class="case-scroll glass" href="#screens">Посмотреть интерфейсы ${icon('arrow')}</a></div></section></div>
<section class="case-brief wrap"><span class="eyebrow">Задача и решение</span><h2>${p.section}</h2><p>${p.sub}</p></section>
<section class="case-showcase wrap" id="screens" aria-label="Интерфейсы ${p.name}"><div class="showcase-grid">${p.features.map(([title,desc,aside,file,ico],i)=>`<article class="showcase-card ${p.theme==='tailcare'||file.includes('dashboard')?'showcase-wide':''} showcase-${i}"><div class="showcase-copy"><span class="feature-number">0${i+1}</span><h3>${title}</h3><p>${desc}</p></div><div class="showcase-art">${screen(p,file)}<span class="showcase-symbol glass" aria-hidden="true">${icon(ico)}</span></div><div class="showcase-label"><span>${aside}</span>${icon('arrow')}</div></article>`).join('')}</div><p class="screenshot-note">${p.note} Нажмите на экран, чтобы рассмотреть его.</p>${extraGallery(p)}</section>
<section class="case-ecosystem scene" id="features"><div class="case-eco-heading"><span class="eyebrow">Возможности продукта</span><h2>${p.extraTitle}</h2></div><div class="case-orbit-object" aria-hidden="true"></div><div class="feature-orbit">${p.extra.map(([ico,t,d])=>`<article class="orbit-card glass"><span class="glass-icon">${icon(ico)}</span><div><h3>${t}</h3><p>${d}</p></div></article>`).join('')}</div></section>
<section class="details wrap"><div><span class="eyebrow">Продумано внутри</span><h2>Понятно снаружи.<br>Связано внутри.</h2></div><div class="details-list">${p.details.map(([t,d],i)=>`<details><summary>${t}<span>+</span></summary><p>${d}</p></details>`).join('')}</div></section>
<section class="tech-section wrap"><div class="section-heading"><div><span class="eyebrow">Технологии</span><h2>Основа продукта</h2></div><p>${p.infra}</p></div><div class="tech-flow">${p.stack.map(([ico,t,d])=>`<div class="tech-item glass"><span class="tech-logo">${ico.length>1?icon(ico):ico}</span><div><h3>${t}</h3><p>${d}</p></div></div>`).join('')}</div></section><section class="other-cases wrap"><h2>Ещё проекты</h2><div>${cases.filter(c=>c.slug!==p.slug).map(c=>`<a href="/cases/${c.slug}/">${c.name}<span>${c.type}</span>${arrow}</a>`).join('')}</div></section></main>`+footer(true)}
