export const icons = {
 arrow:'M5 19 19 5M5 5h14v14', home:'m3 10 9-7 9 7M5 9v12h5v-7h4v7h5V9', grid:'M3 3h7v7H3zM14 3h7v7h-7zM3 14h7v7H3zM14 14h7v7h-7z', code:'m8 6-6 6 6 6m8-12 6 6-6 6M14 3l-4 18', chat:'M4 3h16v14H9l-5 4z', bolt:'m13 2-9 12h7l-1 8L21 9h-8z', layers:'m12 3 10 5-10 5L2 8zM2 12l10 5 10-5M2 16l10 5 10-5', people:'M9 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8M2 21v-3c0-5 14-5 14 0v3M17 4c5 0 5 8 0 8m2 3c3 0 3 3 3 6', check:'m5 12 4 4L19 6', gift:'M3 9h18v4H3zM5 13v9h14v-9M12 9v13M12 9C2 9 4 1 8 3c3 1 4 6 4 6s1-5 4-6c4-2 6 6-4 6', leaf:'M20 3C5 2 1 10 6 17c7 7 16-1 14-14ZM3 22 15 9', shield:'m12 2 9 4v7c0 5-9 9-9 9s-9-4-9-9V6zM7 12l3 3 7-7', chart:'M4 21V11h3v10m4 0V3h3v18m4 0V7h3v14', pin:'M20 10c0 6-8 12-8 12S4 16 4 10a8 8 0 1 1 16 0ZM15 10a3 3 0 1 1-6 0 3 3 0 0 1 6 0', settings:'M12 3v3m0 12v3M3 12h3m12 0h3M5 5l2 2m10 10 2 2M5 19l2-2M17 7l2-2M16 12a4 4 0 1 1-8 0 4 4 0 0 1 8 0', telegram:'m2 10 20-7-4 18-6-5-4 4v-6l10-8-13 7z'
};
export const icon=(name)=>`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.65" stroke-linecap="round" stroke-linejoin="round" aria-hidden="true"><path d="${icons[name]||icons.arrow}"/></svg>`;
export const arrow=`<span class="round-arrow">${icon('arrow')}</span>`;
export const brand=`<a class="brand" href="/" aria-label="Lancer Agency — главная"><b>LANCER</b><span>AGENCY</span></a>`;
export const cta=(text='Обсудить проект',className='')=>`<a class="button primary ${className}" href="https://t.me/landlancer" target="_blank" rel="noopener noreferrer">${text}${icon('arrow')}</a>`;
export function head(title,description,path='/',theme='blue') {return `<!doctype html><html lang="ru"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover"><title>${title} — Lancer Agency</title><meta name="description" content="${description}"><link rel="canonical" href="https://landlancer.ru${path}"><meta name="theme-color" content="#e6f3ff"><meta property="og:title" content="${title} — Lancer Agency"><meta property="og:description" content="${description}"><meta property="og:image" content="https://landlancer.ru/assets/art/alpine-world.webp"><meta property="og:type" content="website"><meta property="og:url" content="https://landlancer.ru${path}"><link rel="icon" href="/favicon.svg"><link rel="stylesheet" href="/agency.css?v=4"><link rel="stylesheet" href="/vendor/lenis.css"><link rel="stylesheet" href="/experience.css?v=4"><script type="module" src="/experience.mjs?v=4"></script><script src="/agency.js?v=4" defer></script><script type="module" src="/glass-lens.mjs?v=4"></script></head><body class="theme-${theme}" id="top"><a class="skip" href="#main">К содержанию</a>`}
export function nav(isCase=false) {return `<header class="header">${brand}<div class="nav-notch"><nav class="top-nav glass" aria-label="Основная навигация">${isCase?'<a href="#overview">Обзор</a><a href="#screens">Интерфейсы</a><a href="#features">Возможности</a>':'<a href="/#works">Кейсы</a><a href="/#services">Услуги</a><a href="/#contact">Контакты</a>'}</nav></div>${isCase?`<a class="button primary" href="/#works">Все проекты ${icon('arrow')}</a>`:cta()}</header>`}
export function rail(){return `<nav class="side-nav glass" aria-label="Быстрая навигация"><a href="/" aria-label="Главная">${icon('home')}</a><a href="/#works" aria-label="Кейсы">${icon('grid')}</a><a href="/#contact" aria-label="Контакты">${icon('chat')}</a></nav>`}
// Intrinsic sizes reserve the real capture ratio before lazy images arrive.
const captureSizes={
 'gift-home-current.webp':[430,865],'gift-mines-current.webp':[430,865],'gift-upgrade-current.webp':[430,865],
 'gaming-case.webp':[719,1280],'gift-mines-active.webp':[719,1280],
 'gift-upgrade-active.webp':[749,1262],'gift-crash-active.webp':[749,1262],
 'gaming-home.webp':[390,800],'gaming-mines.webp':[390,800],'gaming-upgrade.webp':[390,800],'gaming-crash.webp':[390,800],
 'club-home.webp':[390,844],'club-roulette.webp':[390,844],'club-tasks.webp':[390,844],'club-shop.webp':[375,812],
 '12k-home.webp':[375,812],'12k-missions.webp':[375,812],'12k-shop.webp':[375,812],'12k-dashboard.webp':[1425,869],
 'pets-home.webp':[1425,792],'pets-catalog.webp':[1425,792],'pets-volunteers.webp':[1440,800]
};
export function phone(src,alt,extra=''){const [width,height]=captureSizes[src];return `<button type="button" class="phone ${extra}" data-zoom="/assets/screenshots/${src}" data-caption="${alt}" aria-label="Увеличить: ${alt}"><img src="/assets/screenshots/${src}" alt="${alt}" width="${width}" height="${height}" loading="lazy"></button>`}
export function desktop(src,alt,extra=''){const [width,height]=captureSizes[src];return `<button type="button" class="desktop-screen ${extra}" data-zoom="/assets/screenshots/${src}" data-caption="${alt}" aria-label="Увеличить: ${alt}"><span class="window-bar" aria-hidden="true"><i></i><i></i><i></i><span>${alt.split(':')[0]}</span></span><img src="/assets/screenshots/${src}" alt="${alt}" width="${width}" height="${height}" loading="lazy"></button>`}
export const lightbox=`<dialog class="lightbox" aria-label="Скриншот проекта"><div class="lightbox-toolbar"><p></p><button type="button" aria-label="Закрыть скриншот">Закрыть ${icon('check')}</button></div><img alt=""></dialog>`;
export function footer(compact=false){return `<section class="contact scene ${compact?'contact-case':''}" id="contact"><div class="contact-copy"><span class="eyebrow">LANCER AGENCY</span><h2>Расскажите, что хотите создать.</h2><p>Опишите задачу, пользователей и нужные функции —<br>обсудим объём, сроки и следующий шаг.</p>${cta('Обсудить проект')}</div><div class="contact-object" aria-hidden="true"></div><span class="contact-words">ИДЕИ<br>ТЕХНОЛОГИИ<br>ПРОДУКТЫ<br>РЕЗУЛЬТАТ</span></section><footer class="footer wrap">${brand}<span>© 2026</span><nav aria-label="Навигация в подвале"><a href="/#works">Кейсы</a><a href="/#services">Услуги</a><a href="/#approach">Команда</a></nav><a class="footer-telegram" href="https://t.me/landlancer" target="_blank" rel="noopener noreferrer" aria-label="Написать в Telegram">${icon('telegram')}</a><a href="#top">Наверх ${icon('arrow')}</a></footer>${lightbox}</body></html>`}
