import {icon,cta} from './agency-shared.mjs';

const steps=[
 {title:'Разбираемся в задаче',nav:'Задача',body:'Обсуждаем, кто будет пользоваться продуктом и какую задачу он должен решать. Отделяем нужное для старта от того, что можно добавить позже.',show:'Обсуждаем сценарии и границы первой версии.',result:'План работ и согласованный состав MVP.',widget:`<div class="scope-widget"><span class="widget-label">Пример структуры MVP</span><div class="scope-item"><span>Каталог</span><b>В первую версию</b></div><div class="scope-item"><span>Заявка и уведомление</span><b>В первую версию</b></div><div class="scope-item later"><span>Персональные рекомендации</span><b>Позже</b></div><div class="scope-route"><span>Пользователь</span>${icon('arrow')}<span>Действие</span>${icon('arrow')}<strong>Результат</strong></div></div>`},
 {title:'Собираем будущий интерфейс',nav:'Дизайн',body:'Сначала проверяем логику экранов, затем работаем с композицией, типографикой и деталями. Продумываем мобильную версию вместе с основной.',show:'Показываем макеты и кликабельный прототип до разработки.',result:'Согласованные экраны и сценарии переходов.',widget:`<div class="design-widget"><span class="widget-label">От структуры к оформлению</span><div class="roadmap-toggle" role="group" aria-label="Пример интерфейса"><button type="button" data-design="wire" aria-pressed="true">Прототип</button><button type="button" data-design="visual" aria-pressed="false">Макет</button></div><div class="sample-window" data-design-preview="wire" aria-label="Пример экрана каталога"><div class="sample-bar"><span>Каталог</span><i></i></div><div class="sample-feature"><div><b>Найдите своё</b><span>Подборка в одном месте</span><i>Смотреть</i></div><div class="sample-object" aria-hidden="true">${icon('layers')}</div></div><div class="sample-tiles" aria-hidden="true"><i></i><i></i><i></i></div></div></div>`},
 {title:'Разрабатываем по частям',nav:'Разработка',body:'Собираем интерфейс, серверную логику и интеграции. Проверяем каждый законченный сценарий и показываем его в работающей версии.',show:'Проводим промежуточные демонстрации и собираем обратную связь.',result:'Рабочие функции на тестовом адресе.',widget:`<div class="delivery-widget"><span class="widget-label">Пример движения одной задачи</span><div class="delivery-track"><span class="current" data-delivery-marker="0">В работе</span><span data-delivery-marker="1">На проверке</span><span data-delivery-marker="2">Готово</span></div><div class="delivery-task"><span class="task-symbol">${icon('chat')}</span><div><b>Заявка с сайта</b><span data-delivery-text>Подключаем форму к CRM</span></div></div><div class="delivery-meter" aria-hidden="true"><i></i></div><button class="roadmap-action" type="button" data-delivery-next>Показать следующий шаг ${icon('arrow')}</button><span class="widget-note" data-delivery-status role="status">Демонстрация процесса, не статус вашего проекта.</span></div>`},
 {title:'Проверяем перед запуском',nav:'Проверка',body:'Проходим пользовательские сценарии, проверяем адаптивность и обработку ошибок. Исправляем найденное и повторяем проверку.',show:'Вместе проходим готовый продукт на тестовом адресе.',result:'Проверенная версия и согласование запуска.',widget:`<div class="check-widget"><span class="widget-label">Попробуйте чек-лист приёмки</span><label><input type="checkbox" data-roadmap-check><span>Заявка доходит до получателя</span></label><label><input type="checkbox" data-roadmap-check><span>На телефоне всё удобно</span></label><label><input type="checkbox" data-roadmap-check><span>Ошибки объясняются понятно</span></label><div class="check-summary"><span data-check-status role="status">Отмечено 0 из 3</span><progress value="0" max="3" aria-label="Прогресс демонстрационного чек-листа"></progress></div></div>`},
 {title:'Запускаем и передаём продукт',nav:'Запуск',body:'Публикуем согласованную версию, проверяем её после запуска. Передаём исходный код, доступы и объясняем, как управлять продуктом.',show:'Показываем управление и разбираем вопросы по работе системы.',result:'Продукт на вашем домене и материалы для дальнейшей работы.',widget:`<div class="handoff-widget"><span class="widget-label">Что остаётся у вас</span><div class="handoff-file">${icon('code')}<div><b>Исходный код</b><span>Проект и инструкция по запуску</span></div></div><div class="handoff-file">${icon('shield')}<div><b>Доступы</b><span>Сервисы и управление продуктом</span></div></div><div class="handoff-file">${icon('chat')}<div><b>Демонстрация управления</b><span>Основные действия и ответы на вопросы</span></div></div></div>`}
];

export function roadmap(){return `<section class="development-roadmap wrap" id="approach" aria-labelledby="roadmap-title"><div class="roadmap-intro"><div><h2 id="roadmap-title">Как проходит<br>разработка</h2><p>Вы видите результат на каждом этапе.<br>От первого разговора до работающего продукта.</p></div><p class="roadmap-intro-note">Состав и последовательность работ уточняем под вашу задачу.</p></div><div class="roadmap-layout"><aside class="roadmap-aside"><nav aria-label="Этапы разработки">${steps.map((s,i)=>`<a href="#development-${i+1}"${i===0?' aria-current="step"':''}><span>${String(i+1).padStart(2,'0')}</span>${s.nav}${icon('arrow')}</a>`).join('')}</nav><div class="roadmap-aside-note">${icon('chat')}<p>Важные решения согласуем с вами. Демонстрации помогают увидеть результат и вовремя внести изменения.</p></div>${cta('Обсудить задачу')}</aside><ol class="roadmap-stages">${steps.map((s,i)=>`<li class="roadmap-stage" id="development-${i+1}"><span class="roadmap-node" aria-hidden="true">${String(i+1).padStart(2,'0')}</span><article><div class="roadmap-stage-copy"><h3>${s.title}</h3><p>${s.body}</p><div class="roadmap-review"><span>${icon('chat')} Точка обсуждения</span><p>${s.show}</p></div><div class="roadmap-result"><span>На выходе</span><p>${s.result}</p></div></div><div class="roadmap-widget">${s.widget}</div></article></li>`).join('')}</ol></div></section>`;}
