import {head,nav,rail,icon,arrow,cta,phone,desktop,footer} from './agency-shared.mjs';
export const cases=[
 {slug:'gift-roulette',name:'Gift Roulette',theme:'gift',type:'Telegram Mini App',intro:'Четыре игровых интерфейса, личный кабинет и управление через Telegram.',tags:['Интерфейс','Backend','Telegram-бот'],screens:['gift-mines-active.webp','gaming-case.webp'],hand:'Дарим<br>возможности',section:'Один продукт — четыре игровых режима',sub:'Разные сценарии взаимодействия, общий профиль и единая навигация.',features:[
 ['Кейсы','Каталог предметов и анимированная лента. Отдельный экран результата.','Коллекционные предметы со всего мира Telegram','gaming-case.webp','gift'],
 ['Мины','Интерактивное поле 5 × 5. Визуальные состояния ячеек и обновление интерфейса в ходе раунда.','Продуманная механика и чистый интерфейс','gift-mines-active.webp','grid'],
 ['Апгрейд','Выбор двух предметов, круговой индикатор и анимация результата.','Визуальная обратная связь в реальном времени','gift-upgrade-active.webp','arrow'],
 ['Краш','График в реальном времени, история раундов и синхронизация через WebSocket.','Динамичные раунды и синхронизация с сервером','gift-crash-active.webp','chart']
 ],extraTitle:'Больше, чем игровые экраны',extra:[['people','Личный кабинет','Профиль, настройки и история'],['check','Задания','Список активностей и прогресс'],['gift','Инвентарь','Каталог цифровых предметов'],['settings','Управление','Пользователи, контент и рассылки в Telegram']],extraHand:'Единая<br>экосистема<br>в Telegram',details:[['Единый профиль','Баланс, коллекция подарков, история действий и реферальная программа связаны с одним Telegram-аккаунтом.'],['Серверная логика','Интерфейс показывает подтверждённые сервером результаты. База данных хранит пользователей, предметы и операции.'],['Инструменты оператора','Управление кейсами, призами, заданиями и рассылками через Telegram. Статистика помогает видеть работу продукта.']],stack:[['V','Vue 3','Фронтенд'],['ϟ','FastAPI','Бэкенд'],['telegram','aiogram 3','Telegram-бот'],['layers','PostgreSQL','База данных']],infra:'Docker · nginx · WebSocket',note:'Настоящие интерфейсы Gift Roulette: игровые сценарии и дополнительные экраны приложения.'},
 {slug:'maverick',name:'Maverick',theme:'maverick',type:'Программа лояльности',intro:'От QR-кода на продукте до баллов, достижений и собственного магазина мерча.',tags:['Telegram Mini App','Веб-админка','Интеграции'],screens:['club-home.webp','club-roulette.webp'],hand:'Повод<br>вернуться',section:'Каждый контакт становится частью истории',sub:'Активация, вовлечение и награды — в одном приложении бренда.',features:[
 ['Покупка становится началом','Сканирование QR-кода камерой Telegram или ручной ввод. После активации баллы появляются в личном кабинете.','Один QR-код — одна активация','club-home.webp','shield'],
 ['Награды за участие','Ключи открывают доступ к рулетке. Каталог наград и результаты связаны с балансом участника.','Понятный путь от действия к награде','club-roulette.webp','gift'],
 ['Причина заходить снова','Ежедневные задания, серии посещений, достижения и игровые рейтинги поддерживают регулярное взаимодействие.','Прогресс виден прямо в приложении','club-tasks.webp','chart'],
 ['Магазин внутри Mini App','Каталог мерча, оформление заказов за баллы и статусы. Остатки и товары синхронизируются с МойСклад.','От выбора до получения','club-shop.webp','layers']
 ],extraTitle:'Одна система для бренда и участников',extra:[['shield','QR-активация','Одноразовые коды и история начислений'],['people','Вовлечение','Задания, достижения и рефералы'],['gift','Магазин','Мерч, заказы и остатки'],['settings','Веб-админка','Контент, рассылки и аналитика']],extraHand:'Ближе<br>к своему<br>сообществу',details:[['Учёт баллов','Каждое начисление и списание сохраняется в истории. Ключи для рулетки учитываются отдельно от баллов.'],['Управление программой','Веб-панель объединяет работу с участниками, кодами, наградами, заказами и контентом. Рассылки отправляются через Telegram-бота.'],['Интеграции','МойСклад связывает товары и остатки с магазином. Фоновые задачи обрабатывают синхронизацию и уведомления.']],stack:[['V','Vue 3','Mini App + админка'],['ϟ','FastAPI','Серверная логика'],['telegram','aiogram','Telegram-бот'],['layers','PostgreSQL','Учёт операций']],infra:'Redis · Celery · МойСклад · Docker',note:'Настоящие экраны Maverick. Баланс, задания и каталог показаны на демонстрационных данных.'},
 {slug:'tailcare',name:'TailCare',theme:'tailcare',type:'Сервис помощи питомцам',intro:'Помогаем потерявшимся питомцам вернуться домой, а людям — найти нового друга.',tags:['Веб-сервис','Каталог','Telegram-бот'],screens:['pets-home.webp','pets-catalog.webp'],hand:'Чтобы каждый<br>нашёл свой дом',section:'Забота начинается с понятного действия',sub:'Потерял, нашёл, хочу помочь — для каждой ситуации свой короткий путь.',features:[
 ['Один понятный вход','Главная помогает сразу выбрать свою ситуацию: найти питомца, сообщить о найденном или помочь приюту.','В тревожный момент важна ясность','pets-home.webp','home'],
 ['Питомцы рядом','Каталог с фотографиями, категориями и фильтрами. Город и район помогают сузить поиск.','Нужное объявление — без лишних шагов','pets-catalog.webp','pin'],
 ['Помощь объединяет','Отдельный раздел для волонтёров и организаций. Профили, контакты и информация о том, какая помощь нужна.','Место для тех, кто не остаётся в стороне','pets-volunteers.webp','people']
 ],extraTitle:'Сайт, люди и Telegram связаны',extra:[['chat','Публикация','Создание объявлений через бота'],['shield','Модерация','Проверка перед публикацией'],['pin','География','Город, район и координаты'],['people','Сообщество','Приюты, волонтёры и владельцы']],extraHand:'Помогаем<br>найти<br>друг друга',details:[['Объявление начинается в Telegram','Бот последовательно собирает описание, фотографии и местоположение. После проверки карточка появляется в публичном каталоге.'],['Контекст вместо лишних действий','В подробной карточке собраны сведения о питомце, фотографии и контакты. Координаты можно открыть во внешних картах.'],['Поддержка сообщества','Профили волонтёров и организаций помогают найти поддержку. Для организаций предусмотрена информация о помощи и реквизиты пожертвований.']],stack:[['V','Vue 3','Веб-интерфейс'],['ϟ','FastAPI','REST API'],['telegram','Telegram','Публикация и модерация'],['layers','SQLAlchemy','Работа с данными']],infra:'Адаптивная вёрстка · REST API · Telegram',note:'Настоящие экраны TailCare с демонстрационными объявлениями.'}
];
function screen(p,file,extra=''){return p.theme==='tailcare'?desktop(file,`${p.name}: ${file.includes('home')?'главная':file.includes('volunteers')?'волонтёры':'каталог'}`,extra):phone(file,`${p.name}: ${p.features.find(f=>f[3]===file)?.[0]||'интерфейс'}`,extra)}
function moreScreens(p){return p.theme==='gift'?`<details class="extra-screens"><summary>Ещё интерфейсы проекта <span>+</span></summary><div class="extra-screen-grid">${[['gaming-home.webp','Выбор игры'],['gaming-mines.webp','Поле мин'],['gaming-upgrade.webp','Выбор предметов'],['gaming-crash.webp','Ожидание раунда']].map(([file,label])=>`<figure>${phone(file,`Gift Roulette: ${label}`)}<figcaption>${label}</figcaption></figure>`).join('')}</div></details>`:''}
export function casePage(p){return head(`${p.name} — ${p.type}`,p.intro,`/cases/${p.slug}/`,p.theme)+nav(true)+`<main id="main">
<section class="case-hero scene" id="overview">${rail()}<div class="case-intro"><span class="eyebrow">Кейс проекта</span><h1>${p.name}</h1><h2>${p.type}</h2><p>${p.intro}</p><div class="tags">${p.tags.map(t=>`<span class="glass">${t}</span>`).join('')}</div></div><div class="case-devices">${screen(p,p.screens[0],'device-primary')}${screen(p,p.screens[1],'device-secondary')}</div><span class="hero-callout glass">Просто<br>Удобно<br><small>${p.theme==='tailcare'?'Для каждого':'В Telegram'}</small></span><span class="handwritten">${p.hand}</span></section>
<section class="case-screens wrap" id="screens"><div class="center-heading"><h2>${p.section}</h2><p>${p.sub}</p></div><div class="feature-list">${p.features.map(([title,desc,aside,file,ico],i)=>`<article class="feature-row feature-${i}"><div class="feature-copy"><span class="feature-number">0${i+1}</span><h3>${title}</h3><p>${desc}</p><span class="feature-icon glass">${icon(ico)}</span></div><div class="feature-device">${screen(p,file)}</div><div class="feature-aside"><p>${aside}</p><span class="small-line"></span><span class="floating-icon glass" aria-hidden="true">${icon(ico)}</span></div></article>`).join('')}</div><p class="screenshot-note">${p.note} Нажмите на экран, чтобы рассмотреть его.</p>${moreScreens(p)}</section>
<section class="case-ecosystem scene" id="features"><h2>${p.extraTitle}</h2><div class="feature-orbit">${p.extra.map(([ico,t,d])=>`<article class="orbit-card glass"><span class="feature-icon">${icon(ico)}</span><div><h3>${t}</h3><p>${d}</p></div></article>`).join('')}</div><span class="handwritten">${p.extraHand}</span></section>
<section class="details wrap"><div class="detail-heading"><span class="eyebrow">Продумано внутри</span><h2>За простым интерфейсом —<br>связанные процессы</h2></div><div class="details-list">${p.details.map(([t,d],i)=>`<details><summary><span>0${i+1}</span>${t}<span class="details-plus">+</span></summary><p>${d}</p></details>`).join('')}</div></section>
<section class="tech-section wrap" id="system"><div class="center-heading"><h2>Внутри системы</h2><p>Веб-интерфейс, серверная логика, бот и база данных.</p></div><div class="tech-flow">${p.stack.map(([i,t,s],n)=>`<div class="tech-item glass"><span class="tech-logo logo-${n}">${i.length>1?icon(i):i}</span><div><b>${t}</b><small>${s}</small></div></div>${n<3?'<span class="flow-arrow" aria-hidden="true">→</span>':''}`).join('')}</div><p class="infra">${p.infra}</p></section>
</main>`+footer(true)}

