import {studioFooter} from './studio-sections.mjs';
import {breadcrumbs} from './seo.mjs';
import {productStage} from './product-stage.mjs';
import {head,icon} from './agency-shared.mjs';
export const cases=[
 {slug:'gift-roulette',name:'Gift Roulette',theme:'gift',type:'Telegram Mini App',intro:'Четыре игровых интерфейса, личный кабинет и управление через Telegram.',tags:['Интерфейс','Backend','Telegram-бот'],screens:['gift-mines-active.webp','gaming-case.webp'],hand:'Дарим<br>возможности',section:'Один продукт — четыре игровых режима',sub:'Разные сценарии взаимодействия, общий профиль и единая навигация.',features:[
 ['Кейсы','Каталог предметов и анимированная лента. Отдельный экран результата.','Коллекционные предметы со всего мира Telegram','gaming-case.webp','gift'],
 ['Мины','Интерактивное поле 5 × 5. Визуальные состояния ячеек и обновление интерфейса в ходе раунда.','Продуманная механика и чистый интерфейс','gift-mines-current.webp','grid'],
 ['Апгрейд','Выбор двух предметов, круговой индикатор и анимация результата.','Визуальная обратная связь в реальном времени','gift-upgrade-current.webp','arrow'],
 ['Краш','График в реальном времени, история раундов и синхронизация через WebSocket.','Динамичные раунды и синхронизация с сервером','gift-crash-active.webp','chart']
 ],extraTitle:'Больше, чем игровые экраны',extra:[['people','Личный кабинет','Профиль, настройки и история'],['check','Задания','Список активностей и прогресс'],['gift','Инвентарь','Каталог цифровых предметов'],['settings','Управление','Пользователи, контент и рассылки в Telegram']],extraHand:'Единая<br>экосистема<br>в Telegram',details:[['Единый профиль','Баланс, коллекция подарков, история действий и реферальная программа связаны с одним Telegram-аккаунтом.'],['Серверная логика','Интерфейс показывает подтверждённые сервером результаты. База данных хранит пользователей, предметы и операции.'],['Инструменты оператора','Управление кейсами, призами, заданиями и рассылками через Telegram. Статистика помогает видеть работу продукта.']],stack:[['V','Vue 3','Фронтенд'],['ϟ','FastAPI','Бэкенд'],['telegram','aiogram 3','Telegram-бот'],['layers','PostgreSQL','База данных']],infra:'Docker · nginx · WebSocket',note:'Настоящие интерфейсы Gift Roulette: игровые сценарии и дополнительные экраны приложения.'},
 {slug:'maverick',name:'Maverick',theme:'maverick',type:'Программа лояльности',intro:'От QR-кода на продукте до баллов, достижений и собственного магазина мерча.',tags:['Telegram Mini App','Веб-админка','Интеграции'],screens:['club-home.webp','club-roulette.webp'],hand:'Повод<br>вернуться',section:'Каждый контакт становится частью истории',sub:'Активация, вовлечение и награды — в одном приложении бренда.',features:[
 ['Покупка становится началом','Сканирование QR-кода камерой Telegram или ручной ввод. После активации баллы появляются в личном кабинете.','Один QR-код — одна активация','club-home.webp','shield'],
 ['Награды за участие','Ключи открывают доступ к рулетке. Каталог наград и результаты связаны с балансом участника.','Понятный путь от действия к награде','club-roulette.webp','gift'],
 ['Причина заходить снова','Ежедневные задания, серии посещений, достижения и игровые рейтинги поддерживают регулярное взаимодействие.','Прогресс виден прямо в приложении','club-tasks.webp','chart'],
 ['Магазин внутри Mini App','Каталог мерча, оформление заказов за баллы и статусы. Остатки и товары синхронизируются с МойСклад.','От выбора до получения','club-shop.webp','layers']
 ],extraTitle:'Одна система для бренда и участников',extra:[['shield','QR-активация','Одноразовые коды и история начислений'],['people','Вовлечение','Задания, достижения и рефералы'],['gift','Магазин','Мерч, заказы и остатки'],['settings','Веб-админка','Контент, рассылки и аналитика']],extraHand:'Ближе<br>к своему<br>сообществу',details:[['Учёт баллов','Каждое начисление и списание сохраняется в истории. Ключи для рулетки учитываются отдельно от баллов.'],['Управление программой','Веб-панель объединяет работу с участниками, кодами, наградами, заказами и контентом. Рассылки отправляются через Telegram-бота.'],['Интеграции','МойСклад связывает товары и остатки с магазином. Фоновые задачи обрабатывают синхронизацию и уведомления.']],stack:[['V','Vue 3','Mini App + админка'],['ϟ','FastAPI','Серверная логика'],['telegram','aiogram','Telegram-бот'],['layers','PostgreSQL','Учёт операций']],infra:'Redis · Celery · МойСклад · Docker',note:'Настоящие экраны Maverick. Баланс, задания и каталог показаны на демонстрационных данных.'},
 {slug:'tailcare',name:'TailCare',theme:'tailcare',type:'Сервис помощи питомцам',intro:'Помогаем потерявшимся питомцам вернуться домой, а людям — найти нового друга.',tags:['Веб-сервис','Каталог','Telegram-бот'],screens:['pets-home.webp','pets-catalog.webp'],hand:'Чтобы каждый<br>нашёл свой дом',section:'Забота начинается с понятного действия',sub:'Потерял, нашёл, хочу помочь — для каждой ситуации свой короткий путь.',features:[
 ['Один понятный вход','Главная помогает сразу выбрать свою ситуацию: найти питомца, сообщить о найденном или помочь приюту.','В тревожный момент важна ясность','pets-home.webp','home'],
 ['Питомцы рядом','Каталог с фотографиями, категориями и фильтрами. Город и район помогают сузить поиск.','Нужное объявление — без лишних шагов','pets-catalog.webp','pin'],
 ['Помощь объединяет','Отдельный раздел для волонтёров и организаций. Профили, контакты и информация о том, какая помощь нужна.','Место для тех, кто не остаётся в стороне','pets-volunteers.webp','people']
 ],extraTitle:'Сайт, люди и Telegram связаны',extra:[['chat','Публикация','Создание объявлений через бота'],['shield','Модерация','Проверка перед публикацией'],['pin','География','Город, район и координаты'],['people','Сообщество','Приюты, волонтёры и владельцы']],extraHand:'Помогаем<br>найти<br>друг друга',details:[['Объявление начинается в Telegram','Бот последовательно собирает описание, фотографии и местоположение. После проверки карточка появляется в публичном каталоге.'],['Контекст вместо лишних действий','В подробной карточке собраны сведения о питомце, фотографии и контакты. Координаты можно открыть во внешних картах.'],['Поддержка сообщества','Профили волонтёров и организаций помогают найти поддержку. Для организаций предусмотрена информация о помощи и реквизиты пожертвований.']],stack:[['V','Vue 3','Веб-интерфейс'],['ϟ','FastAPI','REST API'],['telegram','Telegram','Публикация и модерация'],['layers','SQLAlchemy','Работа с данными']],infra:'Адаптивная вёрстка · REST API · Telegram',note:'Настоящие экраны TailCare с демонстрационными объявлениями.'}
];
cases.push({slug:'loyalty',name:'12К',theme:'loyalty',type:'Единая программа лояльности',intro:'Mini App для участников и рабочий кабинет для бизнеса. Покупки, бонусы, задания и коммуникации — в одной системе.',tags:['Telegram Mini App','Кабинет бизнеса','Loyalty API'],screens:['12k-home.webp','12k-dashboard.webp'],hand:'Каждая покупка.<br>Новая связь.',section:'От карты участника до управления бизнесом',sub:'Два интерфейса. Один связанный продукт.',features:[
 ['Карта всегда под рукой','Личная карта с QR-кодом и рублёвым кэшбэком. Быстрый доступ к магазину, играм и адресам точек.','Баланс и карта в одном экране','12k-home.webp','shield'],
 ['Повод вернуться','Ежедневные задания, опросы и достижения. Баллы активности учитываются отдельно от кэшбэка с покупок.','Понятный прогресс участника','12k-missions.webp','chart'],
 ['Награды внутри приложения','Каталог мерча, корзина и оформление доставки. Для каждого предложения видны стоимость и доступность.','От активности — к награде','12k-shop.webp','gift'],
 ['Бизнес видит всю картину','Финансовые результаты, средний чек, активность базы и история операций. Отдельные разделы для клиентов, рассылок и правил программы.','Единый кабинет управления','12k-dashboard.webp','layers']
 ],extraTitle:'Лояльность как часть вашего бизнеса',extra:[['people','Клиенты и сегменты','Профили, группы и история покупок'],['chart','Аналитика','Показатели продаж и активности'],['chat','Коммуникации','Рассылки, события и обратная связь'],['settings','Интеграции','ЭВОТОР, API и webhooks']],details:[['Две самостоятельные валюты','Рублёвый кэшбэк начисляется за подтверждённые покупки. Баллы активности — за задания и другие действия внутри Mini App. Балансы не смешиваются.'],['Один кабинет для команды','Рабочее пространство объединяет клиентскую базу, правила лояльности, аналитику и коммуникации. Права сотрудников определяют доступ к разделам.'],['Связь с кассой и сервисами','Loyalty API обрабатывает операции программы. Для ЭВОТОР предусмотрено отдельное приложение. SMS и Wallet требуют настройки соответствующих провайдеров.']],stack:[['V','Vue 3','Telegram Mini App'],['layers','Nuxt 4','Кабинет бизнеса'],['ϟ','FastAPI','Серверная логика'],['layers','PostgreSQL','Данные и операции']],infra:'Telegram · ЭВОТОР · API · Webhooks',note:'Актуальные интерфейсы 12К сняты 23 сентября 2026 года. Данные участника и показатели бизнеса — демонстрационные.'});
const visualGroups={
 maverick:[['maverick-activation',[0,1]],['maverick-engagement',[2,3]]],
 'gift-roulette':[['gift-games',[0,1]],['gift-rounds',[2,3]]],
 loyalty:[['loyalty-member',[0,1,2]],['loyalty-business',[3]]],
 tailcare:[['tailcare-home',[0]],['tailcare-catalog',[1,2]]]
};
function stories(p){return visualGroups[p.slug].map(([asset,indices])=>{
 const title=indices.map(i=>p.features[i][0]).join(' · '),src=`/assets/case-visuals/${asset}.webp`;
 return `<section class="case-story"><div class="story-copy">${indices.map(i=>{const [t,d,a]=p.features[i];return `<article><h2>${t}</h2><p>${d}</p><span class="story-aside">${a}</span></article>`;}).join('')}</div><figure class="story-art"><button type="button" class="generated-device" data-zoom="${src}" data-caption="${p.name}: ${title}" aria-label="Рассмотреть визуализацию ${p.name}"><img src="${src}" width="1536" height="1024" alt="${p.name}: интерфейсы в настоящих устройствах" loading="lazy"></button><figcaption>${title}</figcaption></figure></section>`;
}).join('');}
export function casePage(p){return head(`${p.name} — ${p.type}`,p.intro,`/cases/${p.slug}/`,p.theme).replace(`class="theme-${p.theme}"`,`class="theme-${p.theme} case-editorial"`)+`
<header class="case-header"><a class="case-brand" href="/">${icon('layers')} Lancer Agency</a><nav aria-label="Навигация по кейсу"><a href="#overview">Обзор</a><a href="#screens">Экраны</a><a href="#demo">Попробовать</a></nav><a class="case-back" href="/#works">Все проекты ↗</a></header>
<main id="main"><section class="case-opening" id="overview"><div class="case-opening-copy"><div>${breadcrumbs(`/cases/${p.slug}/`,p.name)}<h1>${p.name}</h1><p class="case-type">${p.type}</p></div><div class="case-opening-note"><p>${p.intro}</p><div class="case-pills">${p.tags.map(t=>`<span>${t}</span>`).join('')}</div><a class="case-play" href="#demo">Попробовать продукт ${icon('arrow')}</a></div></div></section>
<section class="case-story-intro" id="screens"><h2>${p.section}</h2><p>${p.sub}</p></section>
<p class="case-visual-note">Визуализации на основе интерфейсов. Механику продукта можно проверить в демо.</p><div class="case-stories">${stories(p)}</div>
<section class="case-demo-section"><div class="case-demo-heading"><h2>Попробуйте сами.</h2><p>Интерактивный фрагмент ${p.name}. Можно нажимать и исследовать.</p></div>${productStage(p)}</section>
<section class="case-capabilities" id="features"><div><h2>${p.extraTitle}</h2></div><div class="case-capability-grid">${p.extra.map(([ico,t,d])=>`<article>${icon(ico)}<h3>${t}</h3><p>${d}</p></article>`).join('')}</div></section>
<section class="case-details"><h2>Как устроен продукт</h2><div>${p.details.map(([t,d])=>`<details><summary>${t}<span>+</span></summary><p>${d}</p></details>`).join('')}</div></section>
<section class="case-stack"><h2>Технологии</h2><p>${p.infra}</p><div>${p.stack.map(([ico,t,d])=>`<span><strong>${t}</strong><small>${d}</small></span>`).join('')}</div></section>
<section class="case-related"><h2>Ещё проекты</h2><div>${cases.filter(c=>c.slug!==p.slug).map(c=>`<a href="/cases/${c.slug}/"><img src="/assets/covers/${c.slug}.webp" width="1536" height="1024" alt="" loading="lazy"><span>${c.name} ${icon('arrow')}</span><small>${c.type}</small></a>`).join('')}</div></section></main><dialog class="lightbox" aria-label="Изображение проекта"><div class="lightbox-toolbar"><p></p><button type="button" aria-label="Закрыть изображение">Закрыть ${icon('check')}</button></div><img alt=""></dialog>`+studioFooter().replaceAll('href="#','href="/#');}
