import {site,services,faq,caseMeta} from './seo-data.mjs';
export const escapeHtml = value => String(value).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const json = data => JSON.stringify(data).replace(/</g,'\\u003c');
export function metadata(title,description,path){
 if(path==='/')return ['Разработка сайтов, Mini Apps и CRM', 'Lancer Agency — разработка сайтов, Telegram Mini Apps, CRM и автоматизации для бизнеса. Дизайн, серверная часть и интеграции. Посмотрите кейсы и обсудите проект.'];
 const slug=path.split('/')[2];
 if(path.startsWith('/cases/')&&caseMeta[slug])return caseMeta[slug];
 return [title,description];
}
export function breadcrumbItems(path,title){return [{name:'Главная',url:site.url+'/'},...(path.startsWith('/services/')?[{name:'Услуги',url:site.url+'/#services'}]:path.startsWith('/cases/')?[{name:'Кейсы',url:site.url+'/#works'}]:[]),{name:title,url:site.url+path}];}
export function breadcrumbs(path,title){return `<nav class="seo-breadcrumbs" aria-label="Хлебные крошки"><ol>${breadcrumbItems(path,title).map((item,i,items)=>`<li>${i===items.length-1?`<span aria-current="page">${escapeHtml(item.name)}</span>`:`<a href="${escapeHtml(item.url.replace(site.url,''))}">${escapeHtml(item.name)}</a>`}</li>`).join('')}</ol></nav>`;}
export function seoHead(inputTitle,inputDescription,path){
 const [title,description]=metadata(inputTitle,inputDescription,path),url=site.url+path,image=site.url+'/assets/seo/social.png';
 const noindex=path==='/404.html'||path==='/privacy/';
 const service=services.find(s=>path===`/services/${s.slug}/`);
 const organization={'@type':'Organization','@id':site.url+'/#organization',name:site.name,url:site.url+'/',logo:{'@type':'ImageObject',url:site.url+'/assets/brand/lancer.webp',width:800,height:320},description:'Разработка сайтов, Telegram Mini Apps, CRM и автоматизации для бизнеса.',sameAs:[site.contact],contactPoint:{'@type':'ContactPoint',contactType:'Обсуждение проекта',url:site.contact,availableLanguage:'ru'}};
 const webpage={'@type':'WebPage','@id':url+'#page',url,name:title+' — '+site.name,description,inLanguage:'ru',isPartOf:{'@id':site.url+'/#website'},about:{'@id':site.url+'/#organization'}};
 const graph=[organization,{'@type':'WebSite','@id':site.url+'/#website',url:site.url+'/',name:site.name,inLanguage:'ru',publisher:{'@id':site.url+'/#organization'}},webpage];
 if(path!=='/'&&!noindex)graph.push({'@type':'BreadcrumbList',itemListElement:breadcrumbItems(path,title).map((item,i)=>({'@type':'ListItem',position:i+1,name:item.name,item:item.url}))});
 const offered=path==='/'?services:service?[service]:[];
 for(const s of offered)graph.push({'@type':'Service','@id':site.url+`/services/${s.slug}/#service`,name:s.name,serviceType:s.title,description:s.intro,url:site.url+`/services/${s.slug}/`,provider:{'@id':site.url+'/#organization'}});
 const answers=path==='/'?faq:service?.faq;
 if(answers)graph.push({'@type':'FAQPage','@id':url+'#faq',mainEntity:answers.map(([q,a])=>({'@type':'Question',name:q,acceptedAnswer:{'@type':'Answer',text:a}}))});
 return `<title>${escapeHtml(title)} — ${site.name}</title><meta name="description" content="${escapeHtml(description)}"><meta name="robots" content="${noindex?'noindex, follow':'index, follow, max-image-preview:large'}"><link rel="canonical" href="${url}"><meta property="og:title" content="${escapeHtml(title)} — ${site.name}"><meta property="og:description" content="${escapeHtml(description)}"><meta property="og:url" content="${url}"><meta property="og:type" content="website"><meta property="og:locale" content="ru_RU"><meta property="og:site_name" content="${site.name}"><meta property="og:image" content="${image}"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Lancer Agency — сайты, Mini Apps и CRM"><meta name="twitter:card" content="summary_large_image"><meta name="twitter:title" content="${escapeHtml(title)} — ${site.name}"><meta name="twitter:description" content="${escapeHtml(description)}"><meta name="twitter:image" content="${image}"><meta name="twitter:image:alt" content="Lancer Agency — сайты, Mini Apps и CRM"><script type="application/ld+json">${json({'@context':'https://schema.org','@graph':graph})}</script>`;
}
const arrow = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.5" aria-hidden="true"><path d="M6 18 18 6M6 6h12v12"/></svg>';
export function faqBlock(answers=faq){return `<section class="seo-faq wrap" id="faq" aria-labelledby="faq-title"><div class="faq-intro"><h2 id="faq-title">Вопросы<br> о разработке</h2><p>Объём работ определяем под вашу задачу. Здесь — ответы на вопросы перед стартом.</p><a class="faq-contact" href="${site.contact}" target="_blank" rel="noopener noreferrer"><span>Обсудим вашу идею<span>Написать в Telegram</span></span>${arrow}</a></div><div class="faq-answers">${answers.map(([q,a])=>`<details><summary><span>${escapeHtml(q)}</span><i aria-hidden="true"></i></summary><p>${escapeHtml(a)}</p></details>`).join('')}</div></section>`;}
export function aboutBlock(){return `<section class="seo-about wrap" id="about" aria-labelledby="about-title"><div class="about-surface"><div class="about-heading"><h2 id="about-title">Lancer Agency</h2><p class="about-statement">Дизайн и технологии.<br>Один цельный продукт.</p><a class="about-contact" href="${site.contact}" target="_blank" rel="noopener noreferrer">Обсудить проект ${arrow}</a></div><div class="about-description"><p>Разрабатываем сайты, Telegram Mini Apps и рабочие системы для бизнеса. Соединяем дизайн интерфейса, серверную логику и интеграции в один продукт — от согласования задачи до передачи проекта.</p><div class="about-work"><h3>Посмотрите, как это работает</h3><p>Настоящие интерфейсы и интерактивные демонстрации наших проектов.</p><nav aria-label="Проекты агентства"><a href="/cases/maverick/">Maverick ${arrow}</a><a href="/cases/loyalty/">12К ${arrow}</a><a href="/cases/gift-roulette/">Gift Roulette ${arrow}</a><a href="/cases/tailcare/">TailCare ${arrow}</a></nav><a class="about-archive" href="/cases/profimatika/">ProfiMatika · архивный кейс ${arrow}</a></div></div></div></section>`;}
export function serviceLinks(){return `<nav class="seo-links wrap" aria-label="Направления разработки">${services.map(s=>`<a href="/services/${s.slug}/">${s.name}</a>`).join('')}<a href="/#about">Об агентстве</a><a href="/#contact">Контакты</a><a href="/privacy/">Конфиденциальность</a></nav>`;}
